server:
  port: 8083
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/order_service_db

# User Service 호출에 대한 회복성 패턴
resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      user-service:
        sliding-window-type: count-based
        sliding-window-size: 3
        minimum-number-of-calls: 3
        failure-rate-threshold: 50 # 50% 실패 시 Circuit Open
        permitted-number-of-calls-in-half-open-state: 2
  retry:
    retryAspectOrder: 2
    instances:
      user-service:
        max-attempts: 2
        wait-duration: 1s


management:
  endpoints:
    web:
      exposure:
        include: health, info, circuitbreakers, circuitbreakerevents
  endpoint:
    health:
      show-details: always
      probes: 
        enabled: true
  health:
    circuitbreakers:
      enabled: true

