server:
  port: 8085
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://mysql:3306/payment_service_db


management:
  endpoint:
    health:
      probes:
        enabled: true
