apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123qwe"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: TZ
              value: "Asia/Seoul"
          args: # Docker Compose의 command 매핑
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
            - "--skip-character-set-client-handshake"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-initdb          # configmap에서 Sql 파일들 init으로 적용
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: mysql-data
          emptyDir: {} # 운영에서는 PVC 사용
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: msa
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
