apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: 857360183365.dkr.ecr.ap-northeast-2.amazonaws.com/eureka-server:ojg
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "eks" 
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75 -Xms128m -Duser.timezone=Asia/Seoul"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: msa
spec:
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
