server:
  port: 8082
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://mysql:3307/product_service_db
management:
  endpoint:
    health:
      probes:
        enabled: true